version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: toilet_finder_db
    environment:
      POSTGRES_USER: toiletuser
      POSTGRES_PASSWORD: toiletpass
      POSTGRES_DB: toilet_finder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U toiletuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Flask Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: toilet-backend:latest
    container_name: toilet_finder_backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://toiletuser:toiletpass@db:5432/toilet_finder
      - FLASK_ENV=development
      - PORT=5000
    depends_on:
      - db
    volumes:
      - .:/app:rw
    command: gunicorn --bind 0.0.0.0:5000 --workers 2 app:app

volumes:
  postgres_data: